version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: movie_reservation_db_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
      POSTGRES_DB: movie_reservation_db
    ports:
      - "5434:5432" # <-- ALTERADO AQUI (Porta local 5434 redireciona para a porta 5432 do contentor)
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
